Api:
 Version: v1
server:
  port: 9093
  servlet:
    context-path: /users
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: zafar
    driver-class-name:  com.mysql.cj.jdbc.Driver
    
  jpa:
    properties:
       hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true